// examples/lit/src/components/counter-button.ts
import { LitElement, html, css } from 'lit';
import { customElement, state } from 'lit/decorators.js';

@customElement('counter-button')
export class CounterButton extends LitElement {
  @state()
  private count = 0;

  static styles = css`
    button {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.75rem 1.25rem;
      border-radius: 0.5rem;
      border: 1px solid var(--border-color);
      background: var(--bg-secondary);
      color: var(--text-primary);
      cursor: pointer;
      font-weight: 600;
      transition: transform 0.1s ease, background 0.2s ease, border-color 0.2s ease;
      user-select: none;
    }

    button:hover {
      background: #eef2ff;
      border-color: #c7d2fe;
    }

    button:active {
      transform: translateY(1px);
    }

    .badge {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      min-width: 1.5rem;
      height: 1.5rem;
      padding: 0 0.375rem;
      border-radius: 9999px;
      background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
      color: white;
      font-size: 0.75rem;
    }
  `;

  private increment() {
    this.count += 1;
    this.dispatchEvent(new CustomEvent('count-changed', { detail: { count: this.count }, bubbles: true, composed: true }));
  }

  render() {
    return html`
      <button @click=${this.increment} aria-label="Increase counter">
        <span>点击计数</span>
        <span class="badge">${this.count}</span>
      </button>
    `;
  }
}

// examples/vue2/src/components/CounterButton.vue
<template>
  <div class="counter-container">
    <h3 class="counter-title">交互式计数器</h3>
    <div class="counter-display">
      <span class="counter-value">{{ count }}</span>
      <span class="counter-label">次点击</span>
    </div>
    <div class="counter-buttons">
      <button 
        @click="decrement" 
        :disabled="count <= 0"
        class="counter-btn counter-btn--danger"
      >
        ➖ 减少
      </button>
      <button @click="increment" class="counter-btn counter-btn--primary">
        ➕ 增加
      </button>
      <button @click="reset" class="counter-btn counter-btn--secondary">
        🔄 重置
      </button>
    </div>
    <p class="counter-desc">
      这是一个使用 Vue 2 Composition API 构建的响应式计数器组件
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api';

export default defineComponent({
  name: 'CounterButton',
  setup() {
    const count = ref(0);

    const increment = () => {
      count.value++;
    };

    const decrement = () => {
      if (count.value > 0) {
        count.value--;
      }
    };

    const reset = () => {
      count.value = 0;
    };

    return {
      count,
      increment,
      decrement,
      reset,
    };
  },
});
</script>

<style lang="scss" scoped>
.counter-container {
  background: var(--card-background);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  padding: 2rem;
  text-align: center;
  box-shadow: 0 4px 6px -1px var(--shadow-color);
  transition: all 0.3s ease;

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 25px -5px var(--shadow-color);
  }
}

.counter-title {
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0 0 1.5rem 0;
}

.counter-display {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: 2rem;
  padding: 1rem;
  background: var(--background-color);
  border-radius: 8px;
  border: 2px solid var(--primary-color);
}

.counter-value {
  font-size: 3rem;
  font-weight: 800;
  color: var(--primary-color);
  line-height: 1;
  margin-bottom: 0.25rem;
}

.counter-label {
  font-size: 0.875rem;
  color: var(--text-secondary);
  font-weight: 500;
}

.counter-buttons {
  display: flex;
  gap: 0.75rem;
  justify-content: center;
  flex-wrap: wrap;
  margin-bottom: 1rem;
}

.counter-btn {
  padding: 0.75rem 1.25rem;
  border: none;
  border-radius: 8px;
  font-size: 0.875rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  min-width: 100px;

  &:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  }

  &:active:not(:disabled) {
    transform: translateY(0);
  }

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  &--primary {
    background: var(--primary-color);
    color: white;

    &:hover:not(:disabled) {
      background: var(--primary-color-hover);
    }
  }

  &--danger {
    background: var(--danger-color);
    color: white;

    &:hover:not(:disabled) {
      background: var(--danger-color-hover);
    }
  }

  &--secondary {
    background: var(--secondary-color);
    color: white;

    &:hover:not(:disabled) {
      background: var(--secondary-color-hover);
    }
  }

  @media (max-width: 480px) {
    min-width: 80px;
    padding: 0.5rem 1rem;
    font-size: 0.8rem;
  }
}

.counter-desc {
  font-size: 0.875rem;
  color: var(--text-secondary);
  line-height: 1.5;
  margin: 0;
}
</style>
