// examples/lit/src/components/feature-card.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('feature-card')
export class FeatureCard extends LitElement {
  @property({ type: String }) icon = '✨';
  @property({ type: String }) title = '';
  @property({ type: String }) description = '';

  static styles = css`
    .card {
      background: var(--bg-secondary);
      color: var(--text-primary);
      border: 1px solid var(--border-color);
      border-radius: 0.75rem;
      padding: 1.25rem;
      box-shadow: 0 1px 2px rgba(0, 0, 0, 0.03);
      transition: transform 0.15s ease, box-shadow 0.15s ease, border-color 0.15s ease;
    }

    .card:hover {
      transform: translateY(-2px);
      border-color: #cbd5e1;
      box-shadow: 0 8px 20px rgba(0, 0, 0, 0.06);
    }

    .icon {
      font-size: 1.75rem;
      margin-bottom: 0.5rem;
    }

    .title {
      font-size: 1.1rem;
      font-weight: 700;
      margin: 0.25rem 0 0.5rem;
    }

    .desc {
      color: var(--text-secondary);
      line-height: 1.6;
      font-size: 0.95rem;
    }
  `;

  render() {
    return html`
      <div class="card" role="article">
        <div class="icon" aria-hidden="true">${this.icon}</div>
        <div class="title">${this.title}</div>
        <div class="desc">${this.description}</div>
      </div>
    `;
  }
}

// examples/vue2/src/components/FeatureCard.vue
<template>
  <div class="feature-card">
    <div class="feature-icon">{{ icon }}</div>
    <h4 class="feature-title">{{ title }}</h4>
    <p class="feature-description">{{ description }}</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  name: 'FeatureCard',
  props: {
    icon: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
  },
});
</script>

<style lang="scss" scoped>
.feature-card {
  background: var(--card-background);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  padding: 1.5rem;
  text-align: center;
  transition: all 0.3s ease;
  box-shadow: 0 2px 4px -1px var(--shadow-color);

  &:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 25px -5px var(--shadow-color);
    border-color: var(--primary-color);
  }
}

.feature-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
  display: block;
}

.feature-title {
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0 0 0.75rem 0;
}

.feature-description {
  font-size: 0.875rem;
  color: var(--text-secondary);
  line-height: 1.5;
  margin: 0;
}
</style>
