// src/client/react/useAppConfig.ts
/**
 * React Hook - useAppConfig
 * 
 * 使用方式：
 * ```tsx
 * import { useAppConfig } from '@ldesign/launcher/client/react'
 * 
 * function MyComponent() {
 *   const { config, environment } = useAppConfig()
 *   return <div>{config.app.name}</div>
 * }
 * ```
 */

import { useState, useEffect } from 'react'
import { appConfigManager, AppConfig } from '../app-config'

export interface UseAppConfigReturn {
  config: AppConfig
  environment: {
    mode: string
    isDev: boolean
    isProd: boolean
  }
}

export function useAppConfig(): UseAppConfigReturn {
  const [config, setConfig] = useState<AppConfig>(() => appConfigManager.getConfig())
  const [environment] = useState(() => appConfigManager.getEnvironment())

  useEffect(() => {
    // 订阅配置变化
    const unsubscribe = appConfigManager.subscribe((newConfig) => {
      setConfig(newConfig)
    })

    // 组件卸载时取消订阅
    return unsubscribe
  }, [])

  return {
    config,
    environment
  }
}

// src/client/lit/useAppConfig.ts
/**
 * Lit Mixin - AppConfigMixin
 *
 * 使用方式：
 * ```ts
 * import { LitElement, html } from 'lit'
 * import { AppConfigMixin } from '@ldesign/launcher/client/lit'
 *
 * export class MyElement extends AppConfigMixin(LitElement) {
 *   render() {
 *     return html`<div>${this.appConfig.app.name}</div>`
 *   }
 * }
 * ```
 */

import type { ReactiveController, ReactiveControllerHost } from 'lit'
import type { AppConfig } from '../app-config'
import { appConfigManager } from '../app-config'

/**
 * Reactive Controller for App Config
 */
export class AppConfigController implements ReactiveController {
  private host: ReactiveControllerHost
  private unsubscribe: (() => void) | null = null

  config: AppConfig
  environment: {
    mode: string
    isDev: boolean
    isProd: boolean
  }

  constructor(host: ReactiveControllerHost) {
    this.host = host
    this.config = appConfigManager.getConfig()
    this.environment = appConfigManager.getEnvironment()
    host.addController(this)
  }

  hostConnected() {
    // 订阅配置变化
    this.unsubscribe = appConfigManager.subscribe((newConfig) => {
      this.config = newConfig
      this.host.requestUpdate()
    })
  }

  hostDisconnected() {
    // 取消订阅
    if (this.unsubscribe) {
      this.unsubscribe()
    }
  }
}

/**
 * Mixin for App Config (类继承方式)
 */
export function AppConfigMixin<T extends new (...args: any[]) => ReactiveControllerHost>(
  Base: T,
) {
  return class extends Base {
    public _appConfigController = new AppConfigController(this)

    get appConfig() {
      return this._appConfigController.config
    }

    get appEnvironment() {
      return this._appConfigController.environment
    }
  }
}

// 也提供函数式 API
export { getAppConfig, subscribeConfig } from '../app-config'
