// examples/vue2/src/components/ThemeToggle.vue
<template>
  <div class="theme-toggle">
    <label class="toggle-switch">
      <input 
        type="checkbox" 
        :checked="isDark" 
        @change="toggleTheme"
        aria-label="切换主题"
      >
      <span class="slider">
        <span class="slider-icon">
          {{ isDark ? '🌙' : '☀️' }}
        </span>
      </span>
    </label>
    <span class="toggle-label">
      {{ isDark ? '深色' : '浅色' }}
    </span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api';

export default defineComponent({
  name: 'ThemeToggle',
  props: {
    isDark: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['toggle-theme'],
  setup(props, { emit }) {
    const toggleTheme = () => {
      emit('toggle-theme', !props.isDark);
    };

    return {
      toggleTheme,
    };
  },
});
</script>

<style lang="scss" scoped>
.theme-toggle {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  user-select: none;
}

.toggle-label {
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--text-secondary);
  min-width: 2.5rem;
}

.toggle-switch {
  position: relative;
  display: inline-block;
  width: 3.5rem;
  height: 2rem;
  cursor: pointer;

  input {
    opacity: 0;
    width: 0;
    height: 0;

    &:checked + .slider {
      background-color: var(--primary-color);

      &:before {
        transform: translateX(1.5rem);
      }
    }

    &:focus + .slider {
      box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.3);
    }
  }
}

.slider {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: var(--border-color);
  border-radius: 2rem;
  transition: all 0.3s ease;

  &:before {
    content: '';
    position: absolute;
    height: 1.5rem;
    width: 1.5rem;
    left: 0.25rem;
    bottom: 0.25rem;
    background-color: white;
    border-radius: 50%;
    transition: transform 0.3s ease;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  &:hover {
    &:before {
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
    }
  }
}

.slider-icon {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 0.75rem;
  pointer-events: none;
  z-index: 2;
  transition: all 0.3s ease;
}

// 暗色模式下的特殊样式
:global(.dark-theme) .toggle-switch {
  .slider-icon {
    color: #fbbf24;
  }
}
</style>

// examples/lit/src/components/theme-toggle.ts
import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('theme-toggle')
export class ThemeToggle extends LitElement {
  @property({ type: Boolean })
  isDark = false;

  static styles = css`
    .toggle {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.5rem 0.75rem;
      border-radius: 9999px;
      border: 1px solid var(--border-color);
      background: var(--bg-secondary);
      color: var(--text-primary);
      cursor: pointer;
      transition: background 0.2s ease, border-color 0.2s ease;
      user-select: none;
    }

    .toggle:hover {
      background: #f1f5f9;
      border-color: #cbd5e1;
    }

    .dot {
      width: 1rem;
      height: 1rem;
      border-radius: 50%;
      background: currentColor;
      transition: transform 0.2s ease;
    }

    .label {
      font-size: 0.9rem;
    }
  `;

  private toggleTheme() {
    this.isDark = !this.isDark;
    this.dispatchEvent(new CustomEvent('theme-changed', { detail: { isDark: this.isDark }, bubbles: true, composed: true }));
  }

  render() {
    return html`
      <button class="toggle" @click=${this.toggleTheme} aria-pressed=${this.isDark} aria-label="Toggle color theme">
        <span class="dot" style=${`transform: translateX(${this.isDark ? '6px' : '-6px'})`}></span>
        <span class="label">${this.isDark ? '深色模式' : '浅色模式'}</span>
      </button>
    `;
  }
}
